### ISSUE TITLE
Error --- Ethereum

### ISSUE THREAD

**Issue by osizadmin** [hiromaily/go-crypto-wallet#6]
I have faced this issue while run the docker-compose.eth.yml

Creating go-crypto-wallet_eth-node_1 ... 
Creating go-crypto-wallet_eth-node_1 ... error
WARNING: Host is already in use by another container

ERROR: for go-crypto-wallet_eth-node_1  Cannot start service eth-node: driver failed programming external connectivity on endpoint go-crypto-wallet_eth-node_1 (41ad1a314312c8fa2d0459f7Creating go-crypto-wallet_ganache_1  ... done

ERROR: for eth-node  Cannot start service eth-node: driver failed programming external connectivity on endpoint go-crypto-wallet_eth-node_1 (41ad1a314312c8fa2d0459f75a17479922ebfdeb4e1d8c7eeec0977a416e4f36): Bind for 0.0.0.0:8545 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by hiromaily** [comment]
Though there are 2 services on docker-compose.eth.yml, both of them is working for ethereum node. Only one service must be used. run as below
```
docker compose -f docker-compose.eth.yml up eth-node
or
docker compose -f docker-compose.eth.yml up ganache
```
